analyzer:
  plugins:
    - dart_code_metrics
  exclude:
    - build/**
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - lib/**/*.config.dart
  errors:
    # TODO Agree with team on a set of linters which should not be ignored
    omit_local_variable_types: ignore
    #override_on_non_overriding_member: ignore
    prefer_single_quotes: ignore
    prefer_final_fields: ignore
    #return_of_invalid_type_from_closure: ignore
    #sort_child_properties_last: ignore
    todo: ignore
    #type_argument_not_matching_bounds: ignore
    #unawaited_futures: ignore
    #undefined_class: ignore
    #undefined_identifier: ignore
    #undefined_method: ignore
    #unnecessary_new: ignore
    #unnecessary_this: ignore
    #unused_field: ignore
    #unused_import: ignore
    #uri_does_not_exist: ignore
    #unused_catch_clause: ignore
    #unnecessary_null_comparison: ignore
    #unused_local_variable: ignore
    #must_be_immutable: ignore

linter:
  rules:
    - always_declare_return_types
    - always_use_package_imports
    - avoid_empty_else
    - avoid_print
    - cancel_subscriptions
    - close_sinks
    - control_flow_in_finally
    - empty_statements
    - implicit_reopen
    - no_logic_in_create_state
    - prefer_void_to_null
    - use_key_in_widget_constructors
    - file_names
    - leading_newlines_in_multiline_strings
    - library_prefixes
    - null_closures
    - prefer_null_aware_method_calls
    - secure_pubspec_urls
    - annotate_overrides
    - avoid_init_to_null
    - avoid_null_checks_in_equality_operators
    - avoid_relative_lib_imports
    - avoid_return_types_on_setters
    - avoid_shadowing_type_parameters
    - avoid_single_cascade_in_expression_statements
    - avoid_types_as_parameter_names
    - await_only_futures
    - camel_case_extensions
    - curly_braces_in_flow_control_structures
    - empty_catches
    - empty_constructor_bodies
    - library_names
    - no_duplicate_case_values
    - omit_local_variable_types
    - prefer_adjacent_string_concatenation
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_contains
    # - prefer_equal_for_default_values
    - prefer_final_fields
    - prefer_for_elements_to_map_fromIterable
    - prefer_generic_function_type_aliases
    - prefer_if_null_operators
    - prefer_inlined_adds
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_iterable_whereType
    - prefer_single_quotes
    - prefer_spread_collections
    - recursive_getters
    - sort_child_properties_last
    - type_init_formals
    - unawaited_futures
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_getters_setters
    - unnecessary_new
    - unnecessary_null_in_if_null_operators
    - unnecessary_this
    - unrelated_type_equality_checks
    - unsafe_html
    - use_full_hex_values_for_flutter_colors
    - use_function_type_syntax_for_parameters
    - use_rethrow_when_possible
    - valid_regexps
