///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AddLeadRequest {
/*
{
  "user_id": "1",
  "source_id": "1",
  "project_id": "1",
  "location_id": "1",
  "category_id": "1",
  "property_type": "1",
  "property_status": "1",
  "name": "Deepak S",
  "email": "dssh@aa.com",
  "phone": "9874563210",
  "phone_2": "",
  "comment": "text",
  "bdate": "",
  "adate": "",
  "date_time": "2023-05-20 15:28:00",
  "description": "fgfgfg",
  "call_type": "followup"
} 
*/

  String? userId;
  String? sourceId;
  String? projectId;
  String? locationId;
  String? categoryId;
  String? propertyType;
  String? propertyStatus;
  String? name;
  String? email;
  String? phone;
  String? phone_2;
  String? comment;
  String? bdate;
  String? adate;
  String? dateTime;
  String? description;
  String? callType;

  AddLeadRequest({
    this.userId,
    this.sourceId,
    this.projectId,
    this.locationId,
    this.categoryId,
    this.propertyType,
    this.propertyStatus,
    this.name,
    this.email,
    this.phone,
    this.phone_2,
    this.comment,
    this.bdate,
    this.adate,
    this.dateTime,
    this.description,
    this.callType,
  });
  AddLeadRequest.fromJson(Map<String, dynamic> json) {
    userId = json['user_id']?.toString();
    sourceId = json['source_id']?.toString();
    projectId = json['project_id']?.toString();
    locationId = json['location_id']?.toString();
    categoryId = json['category_id']?.toString();
    propertyType = json['property_type']?.toString();
    propertyStatus = json['property_status']?.toString();
    name = json['name']?.toString();
    email = json['email']?.toString();
    phone = json['phone']?.toString();
    phone_2 = json['phone_2']?.toString();
    comment = json['comment']?.toString();
    bdate = json['bdate']?.toString();
    adate = json['adate']?.toString();
    dateTime = json['date_time']?.toString();
    description = json['description']?.toString();
    callType = json['call_type']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['user_id'] = userId;
    data['source_id'] = sourceId;
    data['project_id'] = projectId;
    data['location_id'] = locationId;
    data['category_id'] = categoryId;
    data['property_type'] = propertyType;
    data['property_status'] = propertyStatus;
    data['name'] = name;
    data['email'] = email;
    data['phone'] = phone;
    data['phone_2'] = phone_2;
    data['comment'] = comment;
    data['bdate'] = bdate;
    data['adate'] = adate;
    data['date_time'] = dateTime;
    data['description'] = description;
    data['call_type'] = callType;
    return data;
  }
}
