///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class FollowRequest {
/*
{
  "lead_id": "7535",
  "date_time": "2023-05-20",
  "description": "Test"
} 
*/

  String? leadId;
  String? dateTime;
  String? description;

  FollowRequest({
    this.leadId,
    this.dateTime,
    this.description,
  });
  FollowRequest.fromJson(Map<String, dynamic> json) {
    leadId = json['lead_id']?.toString();
    dateTime = json['date_time']?.toString();
    description = json['description']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['lead_id'] = leadId;
    data['date_time'] = dateTime;
    data['description'] = description;
    return data;
  }
}
