///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GetAllLeadRequest {


  String? userId;

  GetAllLeadRequest({
    this.userId,
  });
  GetAllLeadRequest.fromJson(Map<String, dynamic> json) {
    userId = json['user_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['user_id'] = userId;
    return data;
  }
}
